### ISSUE TITLE
Circular dependencies

### ISSUE THREAD

**Issue by mikaelhg** [bobfoster/peggen-node#1]
`peggen-maven-plugin` depends on `peggen` depends on `peggen-node` depends on `peggen-maven-plugin` ...

**Comment by mikaelhg** [comment]
Closing ticket on defunct project. Issue still exists.

**Comment by bobfoster** [comment]
What issue? Yes, there's a circular dependency in the pom, which is dumb,
but it's not used and the project builds.

**Comment by mikaelhg** [comment]
Back in July 2014 I was trying to build these projects, and they certainly didn't build at that time.

Perhaps things have changed since.

**Comment by bobfoster** [comment]
Well, that was the bug report to make. :) peggen-node builds, but maybe
it's my local repo satisfying the maven plugin dependency. When I get a
chance I'll make sure they build with a clean repo.

**Comment by bobfoster** [comment]
Hi Mikael,

Finally got around to fixing the circular dependency. Thanks for the
report. Sorry you were bummed out.

Bob
